---
- name: Show network facts
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather interface info per host
      ansible.builtin.set_fact:
        iface_info: |
          {% for item in ansible_interfaces | select('match', '^(ens|enp|eth).*') | list %}
          {{ item }}:
            IP: {{ hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] | default('N/A') }}
            Netmask: {{ hostvars[inventory_hostname]['ansible_' + item]['ipv4']['netmask'] | default('N/A') }}
          {% endfor %}

    - name: Save combined info from all hosts into one file
      ansible.builtin.copy:
        dest: "./all_interfaces.txt"
        content: |
          {% for host in groups['all'] %}
          Host: {{ host }}
          {{ hostvars[host].iface_info | default('No data') }}
          {% endfor %}
        mode: '0644'
      delegate_to: localhost
