new_root_passwd: Viettel#2023
# Static IP
interfaces:
  eth0:
    address: "192.168.0.50/24"
    gateway: "192.168.0.1"
    dns_servers: ["8.8.8.8", "1.1.1.1"]
        
# Mount disks
disks:
  - device: "/dev/vdb"
    partition: "/dev/vdb1"
    mountpoint: "/data1"
    fstype: "ext4"
# NFS Mounts
enable_nfs: yes
nfs_mounts:
  - src: "192.168.0.57:/shares/share-30f4ed15-f350-4d0b-9fb9-95f4faf51ac0"
    path: "/mnt/nfs-share"
    fstype: "nfs4"
    opts: "vers=4,minorversion=0,rw,rsize=1048576,wsize=1048576"

# Teleport configuration
enable_teleport: yes
teleport:
  system: "Test"
  ip: "192.168.0.50"
  ip_local: "192.168.0.50"
  hostname: "Test"