---
- name: Generate config.env per host
  ansible.builtin.template:
    src: install_teleport.sh.j2
    dest: install_teleport.sh
    mode: '0755'

- name: Run install script
  ansible.builtin.shell: ./install_teleport.sh
  register: install_teleport_result

- name: Display install result
  ansible.builtin.debug:
    var: install_teleport_result.stdout
  when: install_teleport_result is defined

- name: Restart teleport service
  ansible.builtin.command: |
    rm -rf /var/lib/teleport
    systemctl daemon-reload
    systemctl restart teleport