---
# tasks file for config_server
- name: Static IP configuration
  ansible.builtin.include_tasks: static_ip.yml
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update and upgrade apt packages
  ansible.builtin.include_tasks: pre-setup.yml
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Mount disk configuration
  ansible.builtin.include_tasks: mount_disk.yml

- name: Mount NFS configuration
  ansible.builtin.include_tasks: mount_nfs.yml
  when: ansible_system == 'Linux' and (enable_nfs | default(false))

- name: Install Teleport Agent
  ansible.builtin.include_tasks: install_teleport.yml
  when: (ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu') and (enable_teleport | default(false))
